# Generated by Django 4.2 on 2024-03-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_remove_like_post_remove_like_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
