# Generated by Django 4.2 on 2024-03-06 09:52

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_remove_instapost_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="media",
            field=models.FileField(
                upload_to=post.models.user_directory_path_for_media,
                verbose_name="Image or Video",
            ),
        ),
    ]
