# Generated by Django 4.2 on 2024-03-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "activity",
            "0003_remove_like_post_like_content_type_like_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
