# Generated by Django 4.2 on 2024-03-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("activity", "0004_alter_like_content_type_alter_like_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "activity"), ("model", "Comment")),
                    models.Q(("app_label", "post"), ("model", "InstaPost")),
                    models.Q(("app_label", "post"), ("model", "Story")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
