# Generated by Django 4.2 on 2024-02-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=50, unique=True, verbose_name="Email"
            ),
        ),
    ]
