# Generated by Django 4.2 on 2024-02-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_customuser_is_active_alter_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=50, unique=True, verbose_name="Email"),
        ),
    ]
