# Generated by Django 4.2 on 2024-02-29 18:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_customuser_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="ph_number",
            new_name="phone_number",
        ),
    ]
