# Generated by Django 4.2 on 2024-03-01 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_rename_ph_number_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.IntegerField(
                blank=True,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_registration",
                        message="Enter a valid registration number in the format 09xxxxxxxxx.",
                        regex="(0|\\+98)?([ ]|-|[()]){0,2}9[1|2|3|4]([ ]|-|[()]){0,2}(?:[0-9]([ ]|-|[()]){0,2}){8}",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
    ]
